// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bodata_calon_karyawan.Models.Data;

#nullable disable

namespace bodata_calon_karyawan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bodata_calon_karyawan.Models.Db.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("bodata_calon_karyawan.Models.Db.Biodata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Agama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlamatKtp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlamatTinggal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BersediaDitempatkan")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("GajiDiharapkan")
                        .HasColumnType("numeric");

                    b.Property<string>("GolonganDarah")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KontakDarurat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoKtp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoTelp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PosisiDilamar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TanggalLahir")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TempatLahir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Biodata");
                });

            modelBuilder.Entity("bodata_calon_karyawan.Models.Db.Pekerjaan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BiodataId")
                        .HasColumnType("uuid");

                    b.Property<string>("NamaPerusahaan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PendapatanTerakhir")
                        .HasColumnType("numeric");

                    b.Property<string>("PosisiTerakhir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tahun")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BiodataId");

                    b.ToTable("Pekerjaan");
                });

            modelBuilder.Entity("bodata_calon_karyawan.Models.Db.Pelatihan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BiodataId")
                        .HasColumnType("uuid");

                    b.Property<string>("NamaKursus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Sertifikat")
                        .HasColumnType("boolean");

                    b.Property<int>("Tahun")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BiodataId");

                    b.ToTable("Pelatihan");
                });

            modelBuilder.Entity("bodata_calon_karyawan.Models.Db.Pendidikan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BiodataId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Ipk")
                        .HasColumnType("numeric");

                    b.Property<string>("Jenjang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Jurusan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaInstitusi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TahunLulus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BiodataId");

                    b.ToTable("Pendidikan");
                });

            modelBuilder.Entity("bodata_calon_karyawan.Models.Db.Biodata", b =>
                {
                    b.HasOne("bodata_calon_karyawan.Models.Db.ApplicationUser", "User")
                        .WithMany("Biodatas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("bodata_calon_karyawan.Models.Db.Pekerjaan", b =>
                {
                    b.HasOne("bodata_calon_karyawan.Models.Db.Biodata", "Biodata")
                        .WithMany("PekerjaanList")
                        .HasForeignKey("BiodataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biodata");
                });

            modelBuilder.Entity("bodata_calon_karyawan.Models.Db.Pelatihan", b =>
                {
                    b.HasOne("bodata_calon_karyawan.Models.Db.Biodata", "Biodata")
                        .WithMany("PelatihanList")
                        .HasForeignKey("BiodataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biodata");
                });

            modelBuilder.Entity("bodata_calon_karyawan.Models.Db.Pendidikan", b =>
                {
                    b.HasOne("bodata_calon_karyawan.Models.Db.Biodata", "Biodata")
                        .WithMany("PendidikanList")
                        .HasForeignKey("BiodataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biodata");
                });

            modelBuilder.Entity("bodata_calon_karyawan.Models.Db.ApplicationUser", b =>
                {
                    b.Navigation("Biodatas");
                });

            modelBuilder.Entity("bodata_calon_karyawan.Models.Db.Biodata", b =>
                {
                    b.Navigation("PekerjaanList");

                    b.Navigation("PelatihanList");

                    b.Navigation("PendidikanList");
                });
#pragma warning restore 612, 618
        }
    }
}
